- name: variables from files
  hosts: local
  connection: local
  tasks:
  - name: first playbook
    ansible.builtin.debug:
      msg: "I want to let you know that today is {{TODAY}}, date is {{DATE}} and year is {{YEAR}}"