- name: check value is greater than 10 or not
  hosts: database
  vars:
    my_number: 20
  tasks:
  - name: print if number greater than 20 
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is greater than 20"
    when: my_number > 10

  - name: print if number less than or equal to 20 
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than or equal to 20"
    when: my_number <= 20
  