- name: loop function
  hosts: database
  become: yes
  tasks:
  - name: install software using loop
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
      - git
      - gcc