- name: loop
  hosts: database
  become: yes
  tasks:
  - name: install using loop
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loops:
      - { name: 'git', state: 'present' }
      - { name: 'gcc', state: 'absent' }